# Generated by Django 5.1.6 on 2025-03-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
